houses/urls.py
from django.urls import path
from . import views

app_name = 'houses'

urlpatterns = [
    path('', views.HouseListView.as_view(), name='house-list'),
    path('<int:pk>/', views.HouseDetailView.as_view(), name='house-detail'),
    path('add/', views.HouseCreateView.as_view(), name='house-create'),
    path('<int:pk>/update/', views.HouseUpdateView.as_view(), name='house-update'),
    path('<int:pk>/delete/', views.HouseDeleteView.as_view(), name='house-delete'),
    path('<int:pk>/meterreading/', views.MeterReadingCreateView.as_view(), name='meter-reading-create'),
    path('<int:pk>/meterreading/update/', views.MeterReadingUpdateView.as_view(), name='meter-reading-update'),
    path('<int:pk>/rent/update/', views.RentUpdateView.as_view(), name='rent-update'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tenant.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenant/urls.py
from django.urls import path
from .views import TenantSignUpView, SignUpSuccessView,SignupView

app_name = 'tenant'

urlpatterns = [
    path('signup/', TenantSignUpView.as_view(), name='signup'),
    path('signup/success/', SignUpSuccessView.as_view(), name='signup_success'),
    path('', SignupView.as_view(), name='home'),
]

templates/home/home.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Digitization at Beracah Apartments 1</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
        
    <!-- Canvas -->
    <canvas class="orb-canvas"></canvas>
    <!-- Overlay -->
    <div class="overlay">
    <!-- Overlay inner wrapper -->
    <div class="overlay__inner">
        <!-- Title -->
        <h1 class="overlay__title">
        Digitization at
        <span class="text">Beracah Apartments 1</span>
        </h1>
        <!-- Description -->
        <p class="overlay__description">
        Hi,
        </br> we are currently doing a digitization programme at Beracah Apartments 1, We Require you to add all your personal details in the form and we will get back to you once the system is live and in production
        <strong>Please fill by 7th Friday, June 2023</strong>
        </p>
        <!-- Buttons -->
        <div class="overlay__btns">

        <button class="overlay__btn overlay__btn--primary">
            <a href="{% url 'tenant:signup' %}">

            Tenant Sign up form
            </a>
        </button>

        <button class="overlay__btn overlay__btn--colors">
            <a href="../static/Agreement.docx" target="_blank" download>

            Tenancy agreement
            </a>
        </button>
        
        </div>
    </div>
    </div>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>